import { useEffect, useRef } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useAuth } from '../../../context/AuthContext';
import { useProfile } from '../../profile/hooks/useProfile';
import { getActivePlan, generatePlan } from '../../../services/planService';
import { queryKeys } from '../../../lib/queryKeys';
import type { FitnessPlan, WorkoutSplitStyle } from '../../../types/plan.types';
import type { Profile } from '../../../types/profile.types';

interface UsePlanGeneratorResult {
  plan: FitnessPlan | null;
  profile: Profile | null;
  isLoading: boolean;
  regenerate: (splitStyle?: WorkoutSplitStyle) => Promise<void>;
}

/** Mirrors the web app's usePlanGenerator.ts, including the auto-generate-once guard. */
export function usePlanGenerator(): UsePlanGeneratorResult {
  const { user } = useAuth();
  const { data: profile, isLoading: isProfileLoading } = useProfile();
  const queryClient = useQueryClient();

  const planQuery = useQuery({
    queryKey: queryKeys.plan.active(user?.id ?? ''),
    queryFn: getActivePlan,
    enabled: !!user?.id && !!profile,
  });

  const generateMutation = useMutation({
    mutationFn: (splitStyle: WorkoutSplitStyle | undefined) => generatePlan(splitStyle),
    onSuccess: (newPlan) => {
      if (user) {
        queryClient.setQueryData(queryKeys.plan.active(user.id), newPlan);
      }
    },
  });

  const hasAutoGenerated = useRef(false);

  useEffect(() => {
    if (
      profile &&
      planQuery.isSuccess &&
      planQuery.data === null &&
      !generateMutation.isPending &&
      !hasAutoGenerated.current
    ) {
      hasAutoGenerated.current = true;
      generateMutation.mutate(undefined);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [profile, planQuery.isSuccess, planQuery.data]);

  async function regenerate(splitStyle?: WorkoutSplitStyle) {
    await generateMutation.mutateAsync(splitStyle);
  }

  return {
    plan: planQuery.data ?? null,
    profile: profile ?? null,
    isLoading: isProfileLoading || planQuery.isLoading || generateMutation.isPending,
    regenerate,
  };
}
