// Placeholder legal copy — have it reviewed before launch. A copy lives in
// mobile/src/constants/terms.ts (separate package), keep the two in sync.
export interface TermsSection {
  heading: string;
  body: string;
}

export const TERMS_TITLE = 'Terms and Conditions';

export const TERMS_SECTIONS: TermsSection[] = [
  {
    heading: '1. Acceptance of terms',
    body: 'By creating an AsceNova account you agree to these Terms and Conditions. If you do not agree, please do not create an account or use the service.',
  },
  {
    heading: '2. Not medical advice',
    body: 'AsceNova provides general fitness and nutrition guidance, including AI-generated workout plans and coaching. It is not medical advice. Consult a qualified professional before starting any exercise or nutrition program, especially if you have a health condition, injury, or are pregnant. You exercise at your own risk.',
  },
  {
    heading: '3. Your information',
    body: 'We collect the details you provide (such as name, body measurements, goals, and daily logs) to personalize your plans and track your progress. You are responsible for keeping them accurate. We do not sell your personal data.',
  },
  {
    heading: '4. AI-generated content',
    body: 'Plans and coach replies may be generated by AI and can contain errors. When AI generation is unavailable we may provide a pre-made backup plan chosen to fit your stats. Use your own judgment and stop any exercise that causes pain.',
  },
  {
    heading: '5. Your account',
    body: 'Keep your password confidential. You are responsible for activity on your account. We may suspend accounts that abuse the service, other users, or the leaderboard and challenges.',
  },
  {
    heading: '6. Community conduct',
    body: 'Do not submit false progress data to gain ranks or XP, harass other users, or attempt to disrupt the service.',
  },
  {
    heading: '7. Changes and deletion',
    body: 'We may update these terms; continued use means you accept the updated terms. You can ask for your account to be deleted at any time.',
  },
];
